[tool.semantic_release]
version_variables = ["setup.py:__version__", "camomilla/__init__.py:__version__", "camomilla/theme/__init__.py:__version__"]
[tool.semantic_release.branches.release]
match = "(release)"
prerelease = false
[tool.semantic_release.branches."next"]
match = "next"
prerelease = true
prerelease_token = "beta"
