# Generated by Django 4.2.5 on 2024-10-26 22:34

from django.db import migrations, models
import example.website.models
import structured.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('structured_data', structured.fields.StructuredJSONField(default=example.website.models.init_schema, schema=example.website.models.TestSchema)),
            ],
        ),
    ]
