# Generated by Django 4.2.16 on 2024-11-09 16:10

from django.db import migrations, models
import django.db.models.deletion
import example.website.models
import structured.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleRelationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "structured_data",
                    structured.fields.StructuredJSONField(
                        default=example.website.models.init_schema,
                        schema=example.website.models.TestSchema,
                    ),
                ),
                (
                    "fk_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fk_field",
                        to="website.simplerelationmodel",
                    ),
                ),
                (
                    "m2m_field",
                    models.ManyToManyField(
                        blank=True,
                        related_name="m2m_field",
                        to="website.simplerelationmodel",
                    ),
                ),
            ],
        ),
    ]
