# Generated by Django 4.2.18 on 2025-06-24 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("camomilla", "__first__"),
        ("website", "0002_customargumentsregistermodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPageMetaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                ("og_type", models.CharField(blank=True, max_length=200, null=True)),
                ("og_url", models.CharField(blank=True, max_length=200, null=True)),
                ("canonical", models.CharField(blank=True, max_length=200, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "identifier",
                    models.CharField(
                        default=uuid.uuid4, max_length=200, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breadcrumbs_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("template", models.CharField(blank=True, max_length=500, null=True)),
                ("template_data", models.JSONField(blank=True, default=dict)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUB", "Published"),
                            ("DRF", "Draft"),
                            ("TRS", "Trash"),
                            ("PLA", "Planned"),
                        ],
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("autopermalink", models.BooleanField(default=True)),
                (
                    "custom_field",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "custom_parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_children_pages",
                        to="camomilla.page",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_og_images",
                        to="camomilla.media",
                    ),
                ),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_child_pages",
                        to="website.custompagemetamodel",
                    ),
                ),
                (
                    "url_node",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="camomilla.urlnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Page",
                "verbose_name_plural": "Custom Pages",
            },
        ),
    ]
