# Generated by Django 4.2.18 on 2025-06-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_custompagemetamodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidPageMetaModel",
            fields=[
                (
                    "custompagemetamodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.custompagemetamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ("ordering",),
                "abstract": False,
            },
            bases=("website.custompagemetamodel",),
        ),
    ]
