# Generated by Django 5.2.1 on 2025-07-03 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_invalidpagemetamodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExposedRelatedPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                ("og_type", models.CharField(blank=True, max_length=200, null=True)),
                ("og_url", models.CharField(blank=True, max_length=200, null=True)),
                ("canonical", models.CharField(blank=True, max_length=200, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "identifier",
                    models.CharField(
                        default=uuid.uuid4, max_length=200, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breadcrumbs_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("template", models.CharField(blank=True, max_length=500, null=True)),
                ("template_data", models.JSONField(blank=True, default=dict)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUB", "Published"),
                            ("DRF", "Draft"),
                            ("TRS", "Trash"),
                            ("PLA", "Planned"),
                        ],
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("autopermalink", models.BooleanField(default=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_og_images",
                        to="camomilla.media",
                    ),
                ),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_child_pages",
                        to="website.exposedrelatedpagemodel",
                    ),
                ),
                (
                    "url_node",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="camomilla.urlnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exposed related Page",
                "verbose_name_plural": "Exposed related Pages",
            },
        ),
        migrations.CreateModel(
            name="UnexposedRelatedPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                ("og_type", models.CharField(blank=True, max_length=200, null=True)),
                ("og_url", models.CharField(blank=True, max_length=200, null=True)),
                ("canonical", models.CharField(blank=True, max_length=200, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "identifier",
                    models.CharField(
                        default=uuid.uuid4, max_length=200, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breadcrumbs_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("template", models.CharField(blank=True, max_length=500, null=True)),
                ("template_data", models.JSONField(blank=True, default=dict)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUB", "Published"),
                            ("DRF", "Draft"),
                            ("TRS", "Trash"),
                            ("PLA", "Planned"),
                        ],
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("autopermalink", models.BooleanField(default=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_og_images",
                        to="camomilla.media",
                    ),
                ),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_child_pages",
                        to="website.unexposedrelatedpagemodel",
                    ),
                ),
                (
                    "url_node",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="camomilla.urlnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unexposed related Page",
                "verbose_name_plural": "Unexposed related Pages",
            },
        ),
        migrations.CreateModel(
            name="RelatedPageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                ("og_type", models.CharField(blank=True, max_length=200, null=True)),
                ("og_url", models.CharField(blank=True, max_length=200, null=True)),
                ("canonical", models.CharField(blank=True, max_length=200, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "identifier",
                    models.CharField(
                        default=uuid.uuid4, max_length=200, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breadcrumbs_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("template", models.CharField(blank=True, max_length=500, null=True)),
                ("template_data", models.JSONField(blank=True, default=dict)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUB", "Published"),
                            ("DRF", "Draft"),
                            ("TRS", "Trash"),
                            ("PLA", "Planned"),
                        ],
                        default="DRF",
                        max_length=3,
                    ),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("autopermalink", models.BooleanField(default=True)),
                (
                    "exposed_pages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_pages",
                        to="website.exposedrelatedpagemodel",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_og_images",
                        to="camomilla.media",
                    ),
                ),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_child_pages",
                        to="website.relatedpagemodel",
                    ),
                ),
                (
                    "url_node",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="camomilla.urlnode",
                    ),
                ),
                (
                    "unexposed_pages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_pages",
                        to="website.unexposedrelatedpagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Page",
                "verbose_name_plural": "Related Pages",
            },
        ),
    ]
