# Generated by Django 5.1.1 on 2025-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_exposedrelatedpagemodel_unexposedrelatedpagemodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custompagemetamodel",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="keywords",
            field=models.JSONField(default=list),
        ),
    ]
