# Generated by Django 5.1.1 on 2025-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_custompagemetamodel_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompagemetamodel",
            name="keywords",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="exposedrelatedpagemodel",
            name="keywords",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="relatedpagemodel",
            name="keywords",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="unexposedrelatedpagemodel",
            name="keywords",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
