# Generated by Django 6.0.1 on 2026-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_customapiserializermodel_defaultapiserializermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customapiserializermodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="customapiserializermodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="custompagemetamodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="custompagemetamodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="defaultapiserializermodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="defaultapiserializermodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="exposedrelatedpagemodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="exposedrelatedpagemodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="relatedpagemodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="relatedpagemodel",
            name="status",
        ),
        migrations.RemoveField(
            model_name="unexposedrelatedpagemodel",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="unexposedrelatedpagemodel",
            name="status",
        ),
        migrations.AddField(
            model_name="customapiserializermodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customapiserializermodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="customapiserializermodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="customapiserializermodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customapiserializermodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custompagemetamodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="custompagemetamodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="custompagemetamodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="custompagemetamodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="custompagemetamodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultapiserializermodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="defaultapiserializermodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="defaultapiserializermodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="defaultapiserializermodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultapiserializermodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exposedrelatedpagemodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedpagemodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="draft_data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="has_draft",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unexposedrelatedpagemodel",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
