# Generated by Django 6.0.1 on 2026-05-29 10:44

import django.db.models.deletion
import example.website.models
import structured.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # camomilla migrations are generated on the fly into ``camomilla_migrations``
        # (injected via MIGRATION_MODULES, not committed), so depend on ``__first__``
        # rather than a hard-coded name — matching the other website migrations.
        ("camomilla", "__first__"),
        ("website", "0009_page_lifecycle_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("og_description", models.TextField(blank=True, null=True)),
                ("og_title", models.CharField(blank=True, max_length=200, null=True)),
                ("og_type", models.CharField(blank=True, max_length=200, null=True)),
                ("og_url", models.CharField(blank=True, max_length=200, null=True)),
                ("canonical", models.CharField(blank=True, max_length=200, null=True)),
                ("keywords", models.CharField(blank=True, max_length=200, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "identifier",
                    models.CharField(
                        default=uuid.uuid4, max_length=200, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breadcrumbs_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("template", models.CharField(blank=True, max_length=500, null=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("autopermalink", models.BooleanField(default=True)),
                (
                    "template_data",
                    structured.fields.StructuredJSONField(
                        default=example.website.models._home_default,
                        schema=example.website.models.HomePageData,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_og_images",
                        to="camomilla.media",
                    ),
                ),
                (
                    "parent_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_child_pages",
                        to="website.homepage",
                    ),
                ),
                (
                    "url_node",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="camomilla.urlnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
        ),
    ]
