# Generated by Django 6.0.1 on 2026-05-29 10:46

import example.website.models
import structured.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="autopermalink_en",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="autopermalink_it",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="breadcrumbs_title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="breadcrumbs_title_it",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="canonical_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="canonical_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="description_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="indexable_en",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="indexable_it",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="keywords_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="keywords_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_description_it",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_title_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_type_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_type_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_url_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_url_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="published_at_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="published_at_it",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="template_data_en",
            field=structured.fields.StructuredJSONField(
                default=example.website.models._home_default,
                null=True,
                schema=example.website.models.HomePageData,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="template_data_it",
            field=structured.fields.StructuredJSONField(
                default=example.website.models._home_default,
                null=True,
                schema=example.website.models.HomePageData,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_it",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
